apiVersion: v1
kind: Namespace
metadata:
  name: consent-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-notification-subscription-test
  namespace: consent-manager
  labels:
    app: data-notification-subscription-test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: data-notification-subscription-test
  template:
    metadata:
      labels:
        app: data-notification-subscription-test
    spec:
      containers:
        - name: data-notification-subscription-test
          image: 413379950444.dkr.ecr.us-east-2.amazonaws.com/consent-manager/data-notification-subscription:latest
          env:
          - name: "SERVER_PORT"
            value: "8010"
          # subscriptionmanager
          - name: "DEFAULT_PAGE_SIZE"
            value: "20"
          - name: "MAX_PAGE_SIZE"
            value: "100"
          - name: "SUBSCRIPTION_REQUEST_EXPIRY"
            value: "720"
          # Database
          - name: "POSTGRES_HOST"
            value: "172.16.10.131"
          - name: "POSTGRES_PORT"
            value: "5432"
          - name: "CONSENT_MANAGER_DB_NAME"
            value: "data_notification_subscription"
          - name: "POSTGRES_USER"
            value: "postgres"
          - name: "POSTGRES_PASSWORD"
            value: "8U-BWr9Gz!276zLe"
          - name: "MASTER_POOL_SIZE"
            value: "5"
          - name: "REPLICA_READ_ENABLED"
            value: "false"
          # keycloak
          - name: "KEY_CLOAK_URL"
            value: "https://13.59.3.205:8443/auth"
          - name: "KEY_CLOAK_CONSENT_CLIENT_ID"
            value: "consent-manager"
          - name: "KEY_CLOAK_CONSENT_CLIENT_SECRET"
            value: "e18bcd6c-178f-4335-814e-ce0231f83b1d"
          - name: "KEY_CLOAK_CONSENT_USER_NAME"
            value: "consent-service-admin-user"
          - name: "KEY_CLOAK_CONSENT_PASSWORD"
            value: "welcome"
          - name: "KEY_CLOAK_JWK_URL"
            value: "https://13.59.3.205:8443/auth/realms/vaccination/protocol/openid-connect/certs"
          - name: "KEY_CLOAK_TOKEN_ISSUER"
            value: "https://13.59.3.205:8443/auth/realms/vaccination"
          # gatewayservice
          - name: "GATEWAY_BASE_URL"
            value: "http://aa7e8390b4a8f4363a90f79137f62c68-2022049164.us-east-2.elb.amazonaws.com:8000/v0.5"
          - name: "GATEWAY_REQUEST_TIMEOUT"
            value: "5000"
          - name: "GATEWAY_CLIENT_SECRET"
            value: "3ef83dc1-2ff1-4a7b-8982-b8328237afdf"
          - name: "GATEWAY_CLIENT_ID"
            value: "ncg"
          - name: "CENTRAL_REGISTRY_JWK_URL"
            value: "http://aa7e8390b4a8f4363a90f79137f62c68-2022049164.us-east-2.elb.amazonaws.com:8000/v0.5/certs"
          # authorization
          - name: "AUTHORIZATION_HEADER"
            value: "Authorization"
          - name: "EXTERNAL_IDP_FOR_USER_AUTH"
            value: "false"
          # Valid values are guava(for local), redis
          - name: "CACHE_METHOD"
            value: "guava"
          # Redis Config: Will not be used if cacheMethod is guava
          - name: "REDIS_HOST"
            value: "localhost"
          - name: "REDIS_PORT"
            value: "6379"
          - name: "REDIS_PASSWORD"
            value: "password"
          - name: "REDIS_KEY_EXPIRY"
            value: "5"
          - name: "ROOT_NAMESPACE"
            value: "gateway"
          - name: "KEEP_ALIVE_ENABLED"
            value: "false"
          - name: "REDIS_RETRY"
            value: "0"
          # userservice
          - name: "USER_SERVICE_URL"
            value: "http://a694c24894bb445789feedb879ecaaf7-325014892.us-east-2.elb.amazonaws.com:9000"
          - name: "USER_ID_SUFFIX"
            value: "@ndhm"
          # linkservice
          - name: "LINK_SERVICE_URL"
            value: "http://a694c24894bb445789feedb879ecaaf7-325014892.us-east-2.elb.amazonaws.com:9000"
          # RabbitMQ
          - name: "RABBITMQ_HOST"
            value: "a1147c0a10bd24fd0bf0f7acb4846697-2045861127.us-east-2.elb.amazonaws.com"
          - name: "RABBITMQ_PORT"
            value: "5672"
          - name: "RABBITMQ_USERNAME"
            value: "guest"
          - name: "RABBITMQ_PASSWORD"
            value: "guest"
          # logging
          - name: "LOG_LEVEL"
            value: "INFO"
          # Web Client
          - name: "USE_HTTP_CONNECTION_POOL"
            value: "true"
          # Http Connection Pool
          - name: "HTTP_CONNECTION_POOL_SIZE"
            value: "500"
          - name: "HTTP_CONNECTION_MAX_LIFETIME"
            value: "10"
          - name: "HTTP_CONNECTION_MAX_IDLETIME"
            value: "5"

          ports:
            - containerPort: 8010

